version: '3.8'
services:
  pfgateway:
    build:
      context: .
    container_name: pfgateway
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
