server:
  port: 8080

spring:
  application:
    name: pfgateway
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  expiration: 3600000
  secret: ROWS0BIAS0COIL0WENT0IONS0COED0OWNS0SEND0MARS0LYRA0BAWL0DAY0DEER0IS0BID0OVER0SCAT0WISE0DEAD0HO0LOY0STIR0DADE0ALAN

